//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apuesta
    {
        public int ApuestaId { get; set; }
        public int PartidoId { get; set; }
        public byte GolesLocal { get; set; }
        public byte GolesVisitante { get; set; }
        public string UsuarioId { get; set; }
        public System.DateTime FechaApuesta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Partido Partido { get; set; }
    }
}
