//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    
    public partial class ApuestaFixtureCompleto
    {
        public Nullable<int> ApuestaId { get; set; }
        public Nullable<System.DateTime> FechaApuesta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int TorneoId { get; set; }
        public int PartidoId { get; set; }
        public short GrupoId { get; set; }
        public string Grupo { get; set; }
        public int FechaNumero { get; set; }
        public System.DateTime FechaReal { get; set; }
        public string Local { get; set; }
        public string Visitante { get; set; }
        public Nullable<int> GolesLocal { get; set; }
        public Nullable<int> GolesVisitante { get; set; }
        public Nullable<bool> PermiteApuesta { get; set; }
        public bool EvaluarGanador { get; set; }
        public bool EvaluarLocal { get; set; }
        public bool EvaluarVisitante { get; set; }
        public Nullable<bool> AcertoGanador { get; set; }
        public Nullable<bool> AcertoLocal { get; set; }
        public Nullable<bool> AcertoVisitante { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<bool> ApuestaLocal { get; set; }
        public Nullable<bool> ApuestaVisitante { get; set; }
        public Nullable<bool> ApuestaEmpate { get; set; }
        public Nullable<byte> ApuestaGolesLocal { get; set; }
        public Nullable<byte> ApuestaGolesVisitante { get; set; }
        public Nullable<long> Orden { get; set; }
        public string EscudoLocal { get; set; }
        public string EscudoVisitante { get; set; }
    }
}
