//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    
    public partial class EstadisticasEquipoCompleto
    {
        public Nullable<long> Posicion { get; set; }
        public int TorneoId { get; set; }
        public short GrupoId { get; set; }
        public string Grupo { get; set; }
        public int EquipoId { get; set; }
        public string Equipo { get; set; }
        public string Abreviatura { get; set; }
        public Nullable<int> PartidosJugados { get; set; }
        public Nullable<int> PartidosGanados { get; set; }
        public Nullable<int> PartidosEmpatados { get; set; }
        public Nullable<int> PartidosPerdidos { get; set; }
        public Nullable<int> GolesFavor { get; set; }
        public Nullable<int> GolesContra { get; set; }
        public Nullable<int> Puntos { get; set; }
        public int TorneoGrupoEquipoId { get; set; }
        public string Escudo { get; set; }
    }
}
