//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    
    public partial class FixtureGrupoCompleto
    {
        public int TorneoId { get; set; }
        public string Torneo { get; set; }
        public int PartidoId { get; set; }
        public short GrupoId { get; set; }
        public string Grupo { get; set; }
        public int FechaNumero { get; set; }
        public System.DateTime FechaReal { get; set; }
        public string Local { get; set; }
        public string Visitante { get; set; }
        public Nullable<int> GolesLocal { get; set; }
        public Nullable<int> GolesVisitante { get; set; }
        public Nullable<bool> PermiteApuesta { get; set; }
        public bool EvaluarGanador { get; set; }
        public bool EvaluarLocal { get; set; }
        public bool EvaluarVisitante { get; set; }
        public byte PuntosGanador { get; set; }
        public byte PuntosLocal { get; set; }
        public Nullable<byte> PuntosVisitante { get; set; }
        public int TiempoLimite { get; set; }
        public Nullable<long> Fila { get; set; }
        public string EscudoLocal { get; set; }
        public string EscudoVisitante { get; set; }
    }
}
