//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.TorneosGrupo = new HashSet<TorneoGrupo>();
        }
    
        public short GrupoId { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<TorneoGrupo> TorneosGrupo { get; set; }
    }
}
