//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoApuesta
    {
        public TipoApuesta()
        {
            this.Partidos = new HashSet<Partido>();
        }
    
        public byte TipoApuestaId { get; set; }
        public bool ApuestaGanador { get; set; }
        public byte PuntosGanador { get; set; }
        public bool ApuestaGolesLocal { get; set; }
        public bool ApuestaGolesVisitante { get; set; }
        public byte PuntosGolesLocal { get; set; }
        public Nullable<byte> PuntosGolesVisitante { get; set; }
        public byte PuntosBonus { get; set; }
        public int TiempoLimite { get; set; }
    
        public virtual ICollection<Partido> Partidos { get; set; }
    }
}
