//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        public Torneo()
        {
            this.TorneoEquipos = new HashSet<TorneoEquipo>();
            this.TorneoGrupos = new HashSet<TorneoGrupo>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int TorneoId { get; set; }
        public string Nombre { get; set; }
        public short TipoTorneoId { get; set; }
        public string UrlAmigable { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual TipoTorneo TipoTorneo { get; set; }
        public virtual ICollection<TorneoEquipo> TorneoEquipos { get; set; }
        public virtual ICollection<TorneoGrupo> TorneoGrupos { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
