//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneoGrupoEquipo
    {
        public TorneoGrupoEquipo()
        {
            this.PartidosLocal = new HashSet<Partido>();
            this.PartidosVisitante = new HashSet<Partido>();
        }
    
        public int TorneoId { get; set; }
        public short GrupoId { get; set; }
        public int EquipoId { get; set; }
        public int TorneoGrupoEquipoId { get; set; }
    
        public virtual TorneoEquipo TorneoEquipo { get; set; }
        public virtual TorneoGrupo TorneoGrupo { get; set; }
        public virtual ICollection<Partido> PartidosLocal { get; set; }
        public virtual ICollection<Partido> PartidosVisitante { get; set; }
    }
}
