//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxDev.Prode.Entidades
{
    using System;
    
    public partial class UsuariosPuntajeTorneo
    {
        public int TorneoId { get; set; }
        public string Torneo { get; set; }
        public string UserName { get; set; }
        public int FechaNumero { get; set; }
        public int Puntos { get; set; }
        public Nullable<long> Orden { get; set; }
    }
}
