IF EXISTS(SELECT 1
		  FROM INFORMATION_SCHEMA.COLUMNS I
		  WHERE I.TABLE_NAME = 'Apuesta' 
				AND I.COLUMN_NAME = 'UsuarioId'
				AND I.DATA_TYPE = 'int')
BEGIN

ALTER TABLE dbo.Apuesta
	ALTER COLUMN UsuarioId nvarchar(128) NOT NULL

END
GO
